// <auto-generated />
using System;
using JobHunter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobHunter.Data.Migrations
{
    [DbContext(typeof(JobHunterDbContext))]
    [Migration("20260927084608_RecognizeHomeCity")]
    partial class RecognizeHomeCity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("JobHunter.Domain.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompDiscussed")
                        .HasColumnType("TEXT");

                    b.Property<string>("CvVersion")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitError")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NextAction")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("NextActionDue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusChangedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.FetchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MarkedInactive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarkedStale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Scored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScoringHaltReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("FetchRuns", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplyUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ats")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalApplyUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompCurrency")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CompMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("CompMaxPerYear")
                        .HasColumnType("REAL");

                    b.Property<double?>("CompMin")
                        .HasColumnType("REAL");

                    b.Property<double?>("CompMinPerYear")
                        .HasColumnType("REAL");

                    b.Property<string>("CompPeriod")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryIso")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DropReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentTypeFromSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsRemoteFromSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationText")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissedRuns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostingUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scoring")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Triage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriagedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Settings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptEuropeRemote")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptUnitedStatesRemote")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptedLanguages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AutoRefreshAfterHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompComputedInCurrency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractPreference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasetAtsList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DatasetEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstRunWindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FxOverridesJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("GhostThresholdDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUnitedStatesWorkAuthorization")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HighPayThresholdPerYear")
                        .HasColumnType("REAL");

                    b.Property<string>("HomeCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeCountryIso")
                        .HasColumnType("TEXT");

                    b.Property<bool>("KeepOnsiteWithCompOrRelocation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScoresPerRun")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MinContractorHourly")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinEmploymentAnnual")
                        .HasColumnType("REAL");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RemoteOkEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResumeMarkdownPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumePdfPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetAnnual")
                        .HasColumnType("REAL");

                    b.Property<string>("TitleExcludeTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleIncludeTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WwrEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("JobHunter.Domain.Application", b =>
                {
                    b.OwnsOne("JobHunter.Domain.ApplicationContact", "Contact", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId");

                            b1.Property<string>("Link");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Role");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1
                                .ToJson("Contact")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsMany("JobHunter.Domain.ApplicationHistoryEntry", "History", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<string>("Note");

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.HasKey("ApplicationId", "__synthesizedOrdinal");

                            b1.ToTable("Applications");

                            b1
                                .ToJson("History")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsOne("JobHunter.Domain.ApplicationKit", "Kit", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId");

                            b1.PrimitiveCollection<string>("CallQuestions")
                                .IsRequired();

                            b1.Property<string>("CoverNote")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("FitSummary")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("GeneratedAt");

                            b1.Property<string>("Language")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("LintIssues")
                                .IsRequired();

                            b1.Property<string>("Model")
                                .IsRequired();

                            b1.Property<string>("ResumePath")
                                .IsRequired();

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1
                                .ToJson("Kit")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");

                            b1.OwnsMany("JobHunter.Domain.AtsAnswer", "AtsAnswers", b2 =>
                                {
                                    b2.Property<Guid>("ApplicationKitApplicationId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Answer")
                                        .IsRequired();

                                    b2.Property<string>("Question")
                                        .IsRequired();

                                    b2.HasKey("ApplicationKitApplicationId", "__synthesizedOrdinal");

                                    b2.ToTable("Applications");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicationKitApplicationId");
                                });

                            b1.Navigation("AtsAnswers");
                        });

                    b.OwnsMany("JobHunter.Domain.ApplicationNote", "Notes", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.HasKey("ApplicationId", "__synthesizedOrdinal");

                            b1.ToTable("Applications");

                            b1
                                .ToJson("Notes")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("Contact");

                    b.Navigation("History");

                    b.Navigation("Kit");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("JobHunter.Domain.FetchRun", b =>
                {
                    b.OwnsMany("JobHunter.Domain.ScoringFailureReason", "ScoringFailureReasons", b1 =>
                        {
                            b1.Property<Guid>("FetchRunId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Count");

                            b1.Property<string>("Reason")
                                .IsRequired();

                            b1.HasKey("FetchRunId", "__synthesizedOrdinal");

                            b1.ToTable("FetchRuns");

                            b1
                                .ToJson("ScoringFailureReasons")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("FetchRunId");
                        });

                    b.OwnsMany("JobHunter.Domain.SourceRunResult", "SourceResults", b1 =>
                        {
                            b1.Property<Guid>("FetchRunId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Dropped");

                            b1.Property<string>("Error");

                            b1.Property<int>("Fetched");

                            b1.Property<string>("Kind")
                                .IsRequired();

                            b1.Property<int>("New");

                            b1.Property<int>("Updated");

                            b1.HasKey("FetchRunId", "__synthesizedOrdinal");

                            b1.ToTable("FetchRuns");

                            b1
                                .ToJson("SourceResults")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("FetchRunId");
                        });

                    b.Navigation("ScoringFailureReasons");

                    b.Navigation("SourceResults");
                });

            modelBuilder.Entity("JobHunter.Domain.Job", b =>
                {
                    b.OwnsMany("JobHunter.Domain.JobSourceRef", "Sources", b1 =>
                        {
                            b1.Property<Guid>("JobId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Kind")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("LastSeenAt");

                            b1.Property<string>("SourceId")
                                .IsRequired();

                            b1.HasKey("JobId", "__synthesizedOrdinal");

                            b1.ToTable("Jobs");

                            b1
                                .ToJson("Sources")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsOne("JobHunter.Domain.ScoreCard", "Score", b1 =>
                        {
                            b1.Property<Guid>("JobId");

                            b1.Property<string>("AiMeaning")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("BlockingUnknowns")
                                .IsRequired();

                            b1.Property<string>("CompCurrency");

                            b1.Property<double?>("CompMax");

                            b1.Property<double?>("CompMin");

                            b1.Property<string>("CompPeriod");

                            b1.Property<int>("CompSignal");

                            b1.Property<int>("CompanySignal");

                            b1.Property<int>("ContractForm");

                            b1.Property<string>("DescriptionHashAtScoring")
                                .IsRequired();

                            b1.Property<string>("EmploymentType")
                                .IsRequired();

                            b1.Property<bool?>("EndClientNamed");

                            b1.Property<int>("Level");

                            b1.Property<string>("LevelGuess")
                                .IsRequired();

                            b1.Property<string>("Model")
                                .IsRequired();

                            b1.Property<int>("Niche");

                            b1.Property<string>("Reasoning")
                                .IsRequired();

                            b1.Property<string>("RemotePolicy")
                                .IsRequired();

                            b1.Property<int>("RemoteTimezone");

                            b1.Property<bool?>("RequiresUsAuthorization");

                            b1.Property<DateTimeOffset>("ScoredAt");

                            b1.Property<int>("Stack");

                            b1.Property<string>("TimezoneNote")
                                .IsRequired();

                            b1.Property<int>("Total");

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1
                                .ToJson("Score")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Score");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
