using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace JobHunter.Data.Configurations;

/// <summary>Maps the single settings row; its identifier is always one and is never generated by the database.</summary>
public sealed class SettingsConfiguration : IEntityTypeConfiguration<Domain.Settings>
{
    public void Configure(EntityTypeBuilder<Domain.Settings> builder)
    {
        builder.ToTable("Settings");
        builder.HasKey(settings => settings.Id);
        builder.Property(settings => settings.Id).ValueGeneratedNever();
        builder.Property(settings => settings.ScoreModel).IsRequired();
        builder.Property(settings => settings.KitModel).IsRequired();
        builder.Property(settings => settings.DatasetAtsList).IsRequired();
    }
}
